<a href="https://colab.research.google.com/github/Nafisa-Tasneem/ML_Learning/blob/main/numpy_basics_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

##Basic functions

## Creating numpy array

In [2]:
array1 = np.array([3,2,5,7,0])
print(array1)
print(type(array1))

[3 2 5 7 0]
<class 'numpy.ndarray'>


###ndarray means N dimensional array

In [3]:
arr2 = np.array([[3,2,4,5],[1,55, 6, 7]])
arr2.shape

arr2.dtype

dtype('int64')

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
# we need to define tuple for 2d zeros
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

np.zeros() and np.empty() are not same. the elements of np.zeros() are 0. But the elements of np.empty() are not always 0, they can be garbage values as well. np.empty() allocates memory. 

In [8]:
print(arr2)
arr2*arr2 

[[ 3  2  4  5]
 [ 1 55  6  7]]


array([[   9,    4,   16,   25],
       [   1, 3025,   36,   49]])

In [49]:
arr2 @ arr2.transpose()

array([[  54,  172],
       [ 172, 3111]])

element wise multiplication --> a*b |
 matrix multiplication --> a @ b |
 for matrix multiplication, number of row must be equal to number of column

In [9]:
arr2 + arr2

array([[  6,   4,   8,  10],
       [  2, 110,  12,  14]])

Numpy somewhat works like matlab. but does element wise multiplication and addition. Numpy, matplotlib, scipy all together can replace matlab. And one can work using these in free resources

## Slicing

In [10]:
arr2

array([[ 3,  2,  4,  5],
       [ 1, 55,  6,  7]])

In [11]:
arr3 = np.array([5,4,64,3,3,3])

In [12]:
arr = arr3[4:6]

In [13]:
arr

array([3, 3])

In [14]:
arr[0]= 9

In [15]:
arr3

array([ 5,  4, 64,  3,  9,  3])

Slicing in numpy array is a view. If I write arr = arr3[4:6], then it points the 4-6 index. if I now change arr[0], then the 4th index value will be changed. as arr[0] means arr3[4]. to avoid this, we can copy arr3 to arr. then it will create a new array and new things will be written in a newer array. 

In [16]:
arr = arr3[4:6].copy()
print(arr)
arr[0]= 9
print(arr3)

[9 3]
[ 5  4 64  3  9  3]


In [17]:
arr2

array([[ 3,  2,  4,  5],
       [ 1, 55,  6,  7]])

In [18]:
arr2[0,3] # it prints the 0th index's 3rd indexed value

5

Many fn are written in numpy. we need to use them. 

##Axis, Sorting, and useful numpy functions

In [20]:
ar1 = np.array([[1,2,3], [4,5,6]])

In [21]:
ar1.sum(axis=1) # it does row wise sum (1+2+3, 4+5+6)

array([ 6, 15])

In [22]:
ar1.sum(axis = 0) #it does column wise sum 

array([5, 7, 9])

In [24]:
b = np.array([[7,8,9],[2,8,0]])

In [26]:
ar1.dot(b.transpose()) #matrix multiplication needs 2/3 *3/2 , number of row = number of column

array([[ 50,  18],
       [122,  48]])

In [27]:
## to show all the functions of numpy
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [29]:
len(dir(np))

609

In [32]:
 np.cross(ar1,b)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [34]:
np.sort(ar1)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a = np.arange(6) # gives values from o to 1
a


array([0, 1, 2, 3, 4, 5])

In [46]:
np.arange(10,30,5) # print 10 to 30, with 5 gap

array([10, 15, 20, 25])

In [37]:
b = np.array([1,5,6,3,6,72,637,3,7,5,5,57])
b.shape

(12,)

In [39]:
b = b.reshape(4,3)
b
#reshape function makes matrix from array, reshape(row,column)

array([[  1,   5,   6],
       [  3,   6,  72],
       [637,   3,   7],
       [  5,   5,  57]])

In [43]:
c = np.array([1,5,6,3,6,72,637,3,7,5,5,57])
np.argsort(c)
#argsort gives the sorted index 

array([ 0,  3,  7,  1,  9, 10,  2,  4,  8, 11,  5,  6])

In [45]:
print(np.argmax(b))
print(np.argmin(c))

6
0
